### ISSUE TITLE
64 byte output data swap

### ISSUE THREAD

**Issue by ReinerRieke** [open-power/snap#353]
Once in a while we see that the upper and lower 64 bytes in a cache line are swapped. I will take out an earlier 64 byte swap fix in order to see if that changes anything!

**Comment by jsvogt** [comment]
Circumvention removed, testing

**Comment by luyong6** [comment]
Be careful with the timing of ha_bwad..

**Comment by ReinerRieke** [comment]
So far no 64 byte swap failures have been reported on KU3 and FGT. Will leave the issue open few more days.

**Comment by ibm-genwqe** [comment]
See also https://github.com/open-power/snap/issues/387
We still found a Memory Swap or Data corruption problem on FGT Card. This problem is fixed
in Branch https://github.com/open-power/snap/tree/RC_flip_bit_4_fgt

**Comment by jsvogt** [comment]
Well, not really fixed, but circumvented. Fix must go into the PSL

**Comment by ThomasFuchs** [comment]
Fix went into PSL. Latest version is on IBM OpenPower Portal.
